version: "3.3"

services:
  server:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/public_html:/public_html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/certbot/conf:/etc/nginx/ssl
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
      - ./nginx/favicons:/var/www/path/to/favicons
    ports:
      - 80:80
      - 443:443
    links:
      - api

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email anisutsuri@gmail.com --agree-tos --no-eff-email -d vadimpashkov.xyz
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/logs:/var/log/letsencrypt
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt

  api:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./VolumeData/massage:/var/lib/postgresql/data
